import './globals.css'

import { Box, Container, Flex, HStack, Stack } from 'styled-system/jsx'

import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { MobileSidebarContainer } from '~/components/sidebar/sidebar.mobile'
import { Navbar } from '~/components/navbar/navbar'
import { Sidebar } from '~/components/sidebar/sidebar'
import { layout } from '~/components/recipes/layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Books GPT4 App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const styles = layout()
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.header}>
          <Navbar borderBottomWidth="1px">
            <Box display={{ base: 'block', md: 'none' }}>
              <Container py="1">
                <HStack gap="2">
                  <MobileSidebarContainer>
                    <Sidebar />
                  </MobileSidebarContainer>
                </HStack>
              </Container>
            </Box>
          </Navbar>
        </header>
        <nav className={styles.nav} id="sidebar">
          <Sidebar />
        </nav>
        <main className={styles.main}>
          <slot name="hero" />
          <Flex justify="space-between" py="12" position="relative">
            <Container minWidth="0">
              <Stack gap="12">
                {children}
              </Stack>
            </Container>
          </Flex>
        </main>
      </body>
    </html>
  )
}
